name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: [self-hosted, x86]
    strategy:
      matrix:
        path:
          - qrb_ros_imu
          #TODO this code has formatting issues - qrb_sensor_client
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
